### ISSUE TITLE
Dumping from a 3DS

### ISSUE THREAD

**Issue by Leeo97one** [zoogie/dumpTool#2]
Is it possible to dump the [DSi NAND from a 3DS](https://www.3dbrew.org/wiki/Flash_Filesystem#NAND_structure)? I tried to launch the dumper with [TWMenu++](https://github.com/DS-Homebrew/TWiLightMenu) in DSi mode but the message "This isn't a DSi!" is displayed.

**Comment by zoogie** [comment]
Original DSi and 3DS DSi mode nands have different crypto, hence the refusal of the app to attempt to dump it.

You may use Godmode9 to do things with your DSi nand on 3DS (TWL Nand as it's officially called). There generally isn't any good reason to do that though.

**Comment by Leeo97one** [comment]
OK I see.
In fact I would like to (legally) obtain a DSi NAND from my 3DS without having to buy a DSi for [melonDS](http://melonds.kuribo64.net/faq.php).

So I guess that's out of scope for this tool?

**Comment by zoogie** [comment]
A DSi nand from 3DS is also fundamentally different from a stock DSi nand. It lacks tickets, system titles and files, etc, that melonDS would need to run. Even if it could dump that nand, it would be useless.

**Comment by Leeo97one** [comment]
Oh OK, thanks for the clarification!
